[package]
name = "raytracing"
version = "0.1.0"
authors = ["curekoshimizu <shugo@manabe.mail-box.ne.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.8.0"
rand = "0.8.3"
rayon = "1.5.0"
