[workspace]

members = [
    "sleep",
    "pathlib",
    "async_await",
    "file_io",
    "context_manager",
    "threading",
    "gof",
    "function",
    "async_file_io",
    "web_server",
    "grpc",
    "raytracing",
]
